tab_bar_edge top
tab_bar_style powerline
# tab_bar_style separator
# tab_separator " | "
tab_powerline_style slanted
tab_title_max_length 30
tab_title_template "{fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title}"
# Example using a Nerd Font 'X' icon
# tab_title_template "{title}  \uf00d"
mouse_map middle release grabbed,ungrabbed close_tab

hide_window_decorations no
